# This file was generated by GoReleaser. DO NOT EDIT.
cask "caddy" do
  version "2.11.3"

  on_macos do
    on_intel do
      sha256 "33b694c4967afc39e9dd8421ee5541cfbdd608e50a89c662e98d6654581abfd4"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7395362fb0bf3901370139a03d4237b31d8516b30deac7fab8865276e737e6ec"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fb00343b7b94fe060037880e1dea06fa7a5dd7ecc173c77a8809ccc43cbd0e6"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7de13d6f328e0a27f41a9c83e40328648991b288a028d6103957ca4a3bea4264"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caddy"
  desc "Web Server with custom plugins (cloudflare-dns, security, redis/postgres storage, brotli, rate-limit, layer4, waf)"
  homepage "https://github.com/crazyuploader/caddy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caddy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caddy"] if OS.mac?
  end

  # No zap stanza required
end
