# This file was generated by GoReleaser. DO NOT EDIT.
cask "caddy" do
  version "2.11.4"

  on_macos do
    on_arm do
      sha256 "565334ed79277c1192f9d9566b2dad5eb742cb0448c4c1bc7a55ecc9983c7bb6"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "84387340b4a1d02f12326831a7464867c0deaaf79411958910b706addad2e4e0"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a906a16f598b019dc0143de9fab3278a527554c9261221a3efee29f30b957ad8"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9423c5024f177a2375b321a5e1b0c111aad26e78e9188755b86c5dc91024719"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "caddy"
  desc "Web server with custom plugins (DNS, security, storage, brotli, WAF)"
  homepage "https://github.com/crazyuploader/caddy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caddy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caddy"]
    end
  end

  # No zap stanza required
end
