# This file was generated by GoReleaser. DO NOT EDIT.
cask "caddy" do
  version "2.11.3"

  on_macos do
    on_intel do
      sha256 "dbe33c6e35585bc236c636d154b9dc3ed66e36733b675dc0287ad6da568ca177"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a3be866f1938db51a1816a9fdd3350d6c53b45a4a70e2d35430513e643bc3bf"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "995bfce1b72bfb53da527213284da3cf3aa755ef2965aa9173b5337d8c23f1f2"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c01992147f40b2592ade2adccfb38d486b0fb3c008879e4d46092553275249b"
      url "https://github.com/crazyuploader/caddy/releases/download/v#{version}/caddy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caddy"
  desc "Web Server with custom plugins (cloudflare-dns, security, redis/postgres storage, brotli, rate-limit, layer4, waf)"
  homepage "https://github.com/crazyuploader/caddy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caddy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caddy"] if OS.mac?
  end

  # No zap stanza required
end
