# This file was generated by GoReleaser. DO NOT EDIT.
cask "rclone_exporter" do
  name "rclone_exporter"
  desc "Prometheus exporter for rclone"
  homepage "https://github.com/crazyuploader/rclone_exporter"
  version "1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rclone_exporter"

  on_macos do
    on_intel do
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Darwin_x86_64.tar.gz"
      sha256 "41ec438b176e2c0699eedac89884eb226fafb004a3737ad3e0a425f9e9c490e1"
    end
    on_arm do
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Darwin_arm64.tar.gz"
      sha256 "722da724a13ac36e8c9b8d9f2b8d399dd88a15c554df71b675fca476d29e3073"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Linux_x86_64.tar.gz"
      sha256 "9617f7482ab4563022e35242321e759832b41b2b79a2e47602001587c6e4b0ee"
    end
    on_arm do
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Linux_arm64.tar.gz"
      sha256 "b012dfe2104d00d0ee1dd257192c44117a98647744243916407f7bf0d5e12dfc"
    end
  end

  # No zap stanza required
end
