# This file was generated by GoReleaser. DO NOT EDIT.
cask "rclone_exporter" do
  version "1.6"

  name "rclone_exporter"
  desc "Prometheus exporter for rclone"
  homepage "https://github.com/crazyuploader/rclone_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rclone_exporter"

  on_macos do
    on_intel do
      sha256 "8ee2948672198174a2628969f773c4dc8c704af402414ce623d90259047439aa"
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "56064a0d2d615c0837fd3b4ea6f59ccd2cdb7a2f208b2fa173633dff3072b0e7"
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eec7081aeda164ad9242b971a190b44ad425351f0926ba8b82f73a33a7ac78aa"
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2c041c2b481bafef89334582be623181a1b176d99b6aa563988ea8c27ac3ac4e"
      url "https://github.com/crazyuploader/rclone_exporter/releases/download/v#{version}/rclone_exporter_Linux_arm64.tar.gz"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rclone_exporter"]
    end
  end

  # No zap stanza required
end
