# This file was generated by GitHub Actions. DO NOT EDIT.
cask "tracerate" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "07fc998aeb0e8c2f275506f9161df23b6b5c811f9ccd92c9eecb79873811bef0"
      url "https://github.com/crazyuploader/tracerate/releases/download/v#{version}/tracerate_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0458eea4f2f919bf1b91dfeb5c45766fd99d5ddb015a6f27f015a79d9d66f012"
      url "https://github.com/crazyuploader/tracerate/releases/download/v#{version}/tracerate_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "532c6ac5c363c8ea10f1171d15c6d85eb7626114ce2921d9ac2ee86996fcc134"
      url "https://github.com/crazyuploader/tracerate/releases/download/v#{version}/tracerate_Linux_arm64.tar.gz"
    end
  end

  name "tracerate"
  desc "No-nonsense CLI internet speed tester"
  homepage "https://github.com/crazyuploader/tracerate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracerate"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tracerate"] if OS.mac?
  end

  # No zap stanza required
end
