# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmstats" do
  version "1.0"

  name "vmstats"
  desc "Beautiful terminal UI for monitoring libvirt/KVM virtual machine statistics"
  homepage "https://github.com/crazyuploader/vmstats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmstats"

  on_macos do
    on_intel do
      sha256 "0eeae1d4b9b580cf439dd857e4a8c889d157efe603f9a291fb304b6f1ff7e457"
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "12034c74ab4046fd5c90af450eb521c10eec1b7bf9c0db321849a98b2995e07e"
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9bcdf431b989cd8382336317d8c4f176ec0e080ba4a320675c549d6f64d4018"
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf3f21bb98cef3d15cfcf5f813aa4b5f8dec2a22244cd7cd7d93b7ca88b2482b"
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Linux_arm64.tar.gz"
    end
  end

  # No zap stanza required
end
