# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmstats" do
  name "vmstats"
  desc "A beautiful terminal UI for monitoring libvirt/KVM virtual machine statistics"
  homepage "https://github.com/crazyuploader/vmstats"
  version "1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmstats"

  on_macos do
    on_intel do
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Darwin_x86_64.tar.gz"
      sha256 "80e4874e81eb5cbf84279820f9aa9e0755c5d589e30a9e40830a6e2952601c3e"
    end
    on_arm do
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Darwin_arm64.tar.gz"
      sha256 "bba3dd5eeebc39f342088afd287ff261f8c4f6b8c4c070d4aeb3f848d6d918de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Linux_x86_64.tar.gz"
      sha256 "896b8be18a040211ea1378e2898454c923f78b4b91c4377f99684a17a40ed6f7"
    end
    on_arm do
      url "https://github.com/crazyuploader/vmstats/releases/download/v#{version}/vmstats_Linux_arm64.tar.gz"
      sha256 "8970b15c59163c3c48d2a0c00d5a0cc4cd70074714c272d2b44e3b4d82b77847"
    end
  end

  # No zap stanza required
end
