# This file was generated by GoReleaser. DO NOT EDIT.
cask "watchdog" do
  version "1.0.9"

  on_macos do
    on_intel do
      sha256 "494678b04ed40fe4ccabe34724716f087412cdfb60d73443b195005be032e7bd"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6d37010c324e7a399797c5366b8a044ed0a996c11bed17f0c5fb77aae9555f79"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68216fa1b43e0eb2daf517dcbf45e2bf6f6ab95807bad502a9a58e53989f63d3"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8fb5205ea916061ea7102fe5c1bb1adab672b50e8622c0a3de0e75efe5428f10"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_arm64.tar.gz"
    end
  end

  name "watchdog"
  desc "Lightweight monitoring framework for services with Apprise notifications"
  homepage "https://github.com/crazyuploader/watchdog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watchdog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watchdog"]
    end
  end

  # No zap stanza required

end
