# This file was generated by GoReleaser. DO NOT EDIT.
cask "watchdog" do
  name "watchdog"
  desc "Lightweight monitoring framework for services with Apprise notifications"
  homepage "https://github.com/crazyuploader/watchdog"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watchdog"

  on_macos do
    on_intel do
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_x86_64.tar.gz"
      sha256 "5199e924dcee5ab1876592ca79c39c236c6a8ad0648845fbed5bc581af8126d4"
    end
    on_arm do
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_arm64.tar.gz"
      sha256 "73ee690af1b06bff23c0c34c68a8e9fb1746a70133f39bdb0d2bb1f6f614ac92"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_x86_64.tar.gz"
      sha256 "e8e01f916320ecb005c9e14d5408b64c159f30b3733119ad9ce4aebff90ff771"
    end
    on_arm do
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_arm64.tar.gz"
      sha256 "744c6de6cb4db31ed4b7a92b72bb7ad909e8484ff87c290e1a8902e6182437cf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watchdog"]
    end
  end

  # No zap stanza required
end
