# This file was generated by GoReleaser. DO NOT EDIT.
cask "watchdog" do
  version "1.0.7"

  name "watchdog"
  desc "Lightweight monitoring framework for services with Apprise notifications"
  homepage "https://github.com/crazyuploader/watchdog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watchdog"

  on_macos do
    on_intel do
      sha256 "063323b67db876f2eb786739a131f99b0091c354d90cd321c65e00c5e6eda08d"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8d060e78c311906a6fea748f2eff42e5a1897cfce463f17029f9da385728ae2e"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c501da5e77e7962e1a40c9a93ddf140e9f2c0cb4cf385313d3ae6a00baf81f3"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d234c191c6547a2a67009af0f61ba063bc93e69ce104bb92929ff18839531cc3"
      url "https://github.com/crazyuploader/watchdog/releases/download/v#{version}/watchdog_Linux_arm64.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watchdog"] if OS.mac?
  end

  # No zap stanza required
end
